// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: GameMsgProtocol.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息代号
type MsgCode int32

const (
	MsgCode_USER_ENTRY_CMD          MsgCode = 0
	MsgCode_USER_ENTRY_RESULT       MsgCode = 1
	MsgCode_WHO_ELSE_IS_HERE_CMD    MsgCode = 2
	MsgCode_WHO_ELSE_IS_HERE_RESULT MsgCode = 3
	MsgCode_USER_MOVE_TO_CMD        MsgCode = 4
	MsgCode_USER_MOVE_TO_RESULT     MsgCode = 5
	MsgCode_USER_QUIT_RESULT        MsgCode = 6
	MsgCode_USER_STOP_CMD           MsgCode = 7
	MsgCode_USER_STOP_RESULT        MsgCode = 8
	MsgCode_USER_ATTK_CMD           MsgCode = 9
	MsgCode_USER_ATTK_RESULT        MsgCode = 10
	MsgCode_USER_SUBTRACT_HP_RESULT MsgCode = 11
	MsgCode_USER_DIE_RESULT         MsgCode = 12
	MsgCode_USER_LOGIN_CMD          MsgCode = 13
	MsgCode_USER_LOGIN_RESULT       MsgCode = 14
	MsgCode_SELECT_HERO_CMD         MsgCode = 15
	MsgCode_SELECT_HERO_RESULT      MsgCode = 16
	MsgCode_GET_RANK_CMD            MsgCode = 17
	MsgCode_GET_RANK_RESULT         MsgCode = 18
)

// Enum value maps for MsgCode.
var (
	MsgCode_name = map[int32]string{
		0:  "USER_ENTRY_CMD",
		1:  "USER_ENTRY_RESULT",
		2:  "WHO_ELSE_IS_HERE_CMD",
		3:  "WHO_ELSE_IS_HERE_RESULT",
		4:  "USER_MOVE_TO_CMD",
		5:  "USER_MOVE_TO_RESULT",
		6:  "USER_QUIT_RESULT",
		7:  "USER_STOP_CMD",
		8:  "USER_STOP_RESULT",
		9:  "USER_ATTK_CMD",
		10: "USER_ATTK_RESULT",
		11: "USER_SUBTRACT_HP_RESULT",
		12: "USER_DIE_RESULT",
		13: "USER_LOGIN_CMD",
		14: "USER_LOGIN_RESULT",
		15: "SELECT_HERO_CMD",
		16: "SELECT_HERO_RESULT",
		17: "GET_RANK_CMD",
		18: "GET_RANK_RESULT",
	}
	MsgCode_value = map[string]int32{
		"USER_ENTRY_CMD":          0,
		"USER_ENTRY_RESULT":       1,
		"WHO_ELSE_IS_HERE_CMD":    2,
		"WHO_ELSE_IS_HERE_RESULT": 3,
		"USER_MOVE_TO_CMD":        4,
		"USER_MOVE_TO_RESULT":     5,
		"USER_QUIT_RESULT":        6,
		"USER_STOP_CMD":           7,
		"USER_STOP_RESULT":        8,
		"USER_ATTK_CMD":           9,
		"USER_ATTK_RESULT":        10,
		"USER_SUBTRACT_HP_RESULT": 11,
		"USER_DIE_RESULT":         12,
		"USER_LOGIN_CMD":          13,
		"USER_LOGIN_RESULT":       14,
		"SELECT_HERO_CMD":         15,
		"SELECT_HERO_RESULT":      16,
		"GET_RANK_CMD":            17,
		"GET_RANK_RESULT":         18,
	}
)

func (x MsgCode) Enum() *MsgCode {
	p := new(MsgCode)
	*p = x
	return p
}

func (x MsgCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgCode) Descriptor() protoreflect.EnumDescriptor {
	return file_GameMsgProtocol_proto_enumTypes[0].Descriptor()
}

func (MsgCode) Type() protoreflect.EnumType {
	return &file_GameMsgProtocol_proto_enumTypes[0]
}

func (x MsgCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgCode.Descriptor instead.
func (MsgCode) EnumDescriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{0}
}

//
// 用户入场
///////////////////////////////////////////////////////////////////////
// 指令
type UserEntryCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserEntryCmd) Reset() {
	*x = UserEntryCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEntryCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntryCmd) ProtoMessage() {}

func (x *UserEntryCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntryCmd.ProtoReflect.Descriptor instead.
func (*UserEntryCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{0}
}

// 结果
type UserEntryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户 Id
	UserId uint32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户名称
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// 英雄形象
	HeroAvatar string `protobuf:"bytes,3,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
}

func (x *UserEntryResult) Reset() {
	*x = UserEntryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserEntryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntryResult) ProtoMessage() {}

func (x *UserEntryResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntryResult.ProtoReflect.Descriptor instead.
func (*UserEntryResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{1}
}

func (x *UserEntryResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserEntryResult) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserEntryResult) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

//
// 还有谁在场
///////////////////////////////////////////////////////////////////////
// 指令
type WhoElseIsHereCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhoElseIsHereCmd) Reset() {
	*x = WhoElseIsHereCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoElseIsHereCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoElseIsHereCmd) ProtoMessage() {}

func (x *WhoElseIsHereCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoElseIsHereCmd.ProtoReflect.Descriptor instead.
func (*WhoElseIsHereCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{2}
}

// 结果
type WhoElseIsHereResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户信息数组
	UserInfo []*WhoElseIsHereResult_UserInfo `protobuf:"bytes,1,rep,name=userInfo,proto3" json:"userInfo,omitempty"`
}

func (x *WhoElseIsHereResult) Reset() {
	*x = WhoElseIsHereResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoElseIsHereResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoElseIsHereResult) ProtoMessage() {}

func (x *WhoElseIsHereResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoElseIsHereResult.ProtoReflect.Descriptor instead.
func (*WhoElseIsHereResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{3}
}

func (x *WhoElseIsHereResult) GetUserInfo() []*WhoElseIsHereResult_UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

//
// 用户移动
///////////////////////////////////////////////////////////////////////
// 指令
type UserMoveToCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	// XXX 注意: 用户移动指令中没有用户 Id,
	// 这是为什么?
	//
	// 起始位置 X
	MoveFromPosX float32 `protobuf:"fixed32,1,opt,name=moveFromPosX,proto3" json:"moveFromPosX,omitempty"`
	// 起始位置 Y
	MoveFromPosY float32 `protobuf:"fixed32,2,opt,name=moveFromPosY,proto3" json:"moveFromPosY,omitempty"`
	// 移动到位置 X
	MoveToPosX float32 `protobuf:"fixed32,3,opt,name=moveToPosX,proto3" json:"moveToPosX,omitempty"`
	// 移动到位置 Y
	MoveToPosY float32 `protobuf:"fixed32,4,opt,name=moveToPosY,proto3" json:"moveToPosY,omitempty"`
}

func (x *UserMoveToCmd) Reset() {
	*x = UserMoveToCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMoveToCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMoveToCmd) ProtoMessage() {}

func (x *UserMoveToCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMoveToCmd.ProtoReflect.Descriptor instead.
func (*UserMoveToCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{4}
}

func (x *UserMoveToCmd) GetMoveFromPosX() float32 {
	if x != nil {
		return x.MoveFromPosX
	}
	return 0
}

func (x *UserMoveToCmd) GetMoveFromPosY() float32 {
	if x != nil {
		return x.MoveFromPosY
	}
	return 0
}

func (x *UserMoveToCmd) GetMoveToPosX() float32 {
	if x != nil {
		return x.MoveToPosX
	}
	return 0
}

func (x *UserMoveToCmd) GetMoveToPosY() float32 {
	if x != nil {
		return x.MoveToPosY
	}
	return 0
}

// 结果
type UserMoveToResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 移动用户 Id
	MoveUserId uint32 `protobuf:"varint,1,opt,name=moveUserId,proto3" json:"moveUserId,omitempty"`
	// 起始位置 X
	MoveFromPosX float32 `protobuf:"fixed32,2,opt,name=moveFromPosX,proto3" json:"moveFromPosX,omitempty"`
	// 起始位置 Y
	MoveFromPosY float32 `protobuf:"fixed32,3,opt,name=moveFromPosY,proto3" json:"moveFromPosY,omitempty"`
	// 移动到位置 X
	MoveToPosX float32 `protobuf:"fixed32,4,opt,name=moveToPosX,proto3" json:"moveToPosX,omitempty"`
	// 移动到位置 Y
	MoveToPosY float32 `protobuf:"fixed32,5,opt,name=moveToPosY,proto3" json:"moveToPosY,omitempty"`
	// 启程时间戳
	MoveStartTime uint64 `protobuf:"varint,6,opt,name=moveStartTime,proto3" json:"moveStartTime,omitempty"`
}

func (x *UserMoveToResult) Reset() {
	*x = UserMoveToResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMoveToResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMoveToResult) ProtoMessage() {}

func (x *UserMoveToResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMoveToResult.ProtoReflect.Descriptor instead.
func (*UserMoveToResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{5}
}

func (x *UserMoveToResult) GetMoveUserId() uint32 {
	if x != nil {
		return x.MoveUserId
	}
	return 0
}

func (x *UserMoveToResult) GetMoveFromPosX() float32 {
	if x != nil {
		return x.MoveFromPosX
	}
	return 0
}

func (x *UserMoveToResult) GetMoveFromPosY() float32 {
	if x != nil {
		return x.MoveFromPosY
	}
	return 0
}

func (x *UserMoveToResult) GetMoveToPosX() float32 {
	if x != nil {
		return x.MoveToPosX
	}
	return 0
}

func (x *UserMoveToResult) GetMoveToPosY() float32 {
	if x != nil {
		return x.MoveToPosY
	}
	return 0
}

func (x *UserMoveToResult) GetMoveStartTime() uint64 {
	if x != nil {
		return x.MoveStartTime
	}
	return 0
}

//
// 用户退场
///////////////////////////////////////////////////////////////////////
//
// XXX 注意: 用户退场不需要指令, 因为是在断开服务器的时候执行
//
// 结果
type UserQuitResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 退出用户 Id
	QuitUserId uint32 `protobuf:"varint,1,opt,name=quitUserId,proto3" json:"quitUserId,omitempty"`
}

func (x *UserQuitResult) Reset() {
	*x = UserQuitResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserQuitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQuitResult) ProtoMessage() {}

func (x *UserQuitResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQuitResult.ProtoReflect.Descriptor instead.
func (*UserQuitResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{6}
}

func (x *UserQuitResult) GetQuitUserId() uint32 {
	if x != nil {
		return x.QuitUserId
	}
	return 0
}

//
// 用户停驻
///////////////////////////////////////////////////////////////////////
// 指令
type UserStopCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserStopCmd) Reset() {
	*x = UserStopCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStopCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStopCmd) ProtoMessage() {}

func (x *UserStopCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStopCmd.ProtoReflect.Descriptor instead.
func (*UserStopCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{7}
}

// 结果
type UserStopResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 停驻用户 Id
	StopUserId uint32 `protobuf:"varint,1,opt,name=stopUserId,proto3" json:"stopUserId,omitempty"`
	// 停驻在位置 X
	StopAtPosX float32 `protobuf:"fixed32,2,opt,name=stopAtPosX,proto3" json:"stopAtPosX,omitempty"`
	// 停驻在位置 Y
	StopAtPosY float32 `protobuf:"fixed32,3,opt,name=stopAtPosY,proto3" json:"stopAtPosY,omitempty"`
}

func (x *UserStopResult) Reset() {
	*x = UserStopResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserStopResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStopResult) ProtoMessage() {}

func (x *UserStopResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStopResult.ProtoReflect.Descriptor instead.
func (*UserStopResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{8}
}

func (x *UserStopResult) GetStopUserId() uint32 {
	if x != nil {
		return x.StopUserId
	}
	return 0
}

func (x *UserStopResult) GetStopAtPosX() float32 {
	if x != nil {
		return x.StopAtPosX
	}
	return 0
}

func (x *UserStopResult) GetStopAtPosY() float32 {
	if x != nil {
		return x.StopAtPosY
	}
	return 0
}

//
// 用户攻击
///////////////////////////////////////////////////////////////////////
// 指令
type UserAttkCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 目标用户 Id
	TargetUserId uint32 `protobuf:"varint,1,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
}

func (x *UserAttkCmd) Reset() {
	*x = UserAttkCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAttkCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAttkCmd) ProtoMessage() {}

func (x *UserAttkCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAttkCmd.ProtoReflect.Descriptor instead.
func (*UserAttkCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{9}
}

func (x *UserAttkCmd) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 结果
type UserAttkResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发动攻击的用户 Id
	AttkUserId uint32 `protobuf:"varint,1,opt,name=attkUserId,proto3" json:"attkUserId,omitempty"`
	// 目标用户 Id
	TargetUserId uint32 `protobuf:"varint,2,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
}

func (x *UserAttkResult) Reset() {
	*x = UserAttkResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAttkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAttkResult) ProtoMessage() {}

func (x *UserAttkResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAttkResult.ProtoReflect.Descriptor instead.
func (*UserAttkResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{10}
}

func (x *UserAttkResult) GetAttkUserId() uint32 {
	if x != nil {
		return x.AttkUserId
	}
	return 0
}

func (x *UserAttkResult) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

// 用户减血结果
type UserSubtractHpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 目标用户 Id
	TargetUserId uint32 `protobuf:"varint,1,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
	// 减血量
	SubtractHp uint32 `protobuf:"varint,2,opt,name=subtractHp,proto3" json:"subtractHp,omitempty"`
}

func (x *UserSubtractHpResult) Reset() {
	*x = UserSubtractHpResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserSubtractHpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSubtractHpResult) ProtoMessage() {}

func (x *UserSubtractHpResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSubtractHpResult.ProtoReflect.Descriptor instead.
func (*UserSubtractHpResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{11}
}

func (x *UserSubtractHpResult) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *UserSubtractHpResult) GetSubtractHp() uint32 {
	if x != nil {
		return x.SubtractHp
	}
	return 0
}

// 死亡结果
type UserDieResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 目标用户 Id
	TargetUserId uint32 `protobuf:"varint,1,opt,name=targetUserId,proto3" json:"targetUserId,omitempty"`
}

func (x *UserDieResult) Reset() {
	*x = UserDieResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserDieResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDieResult) ProtoMessage() {}

func (x *UserDieResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDieResult.ProtoReflect.Descriptor instead.
func (*UserDieResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{12}
}

func (x *UserDieResult) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

//
// 用户登录
///////////////////////////////////////////////////////////////////////
// 指令
type UserLoginCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户名称
	UserName string `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	// 用户密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *UserLoginCmd) Reset() {
	*x = UserLoginCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginCmd) ProtoMessage() {}

func (x *UserLoginCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginCmd.ProtoReflect.Descriptor instead.
func (*UserLoginCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{13}
}

func (x *UserLoginCmd) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserLoginCmd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 结果
type UserLoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户 Id,
	// 如果是 -1 则说明登录失败
	UserId uint32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户名称
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// 英雄形象
	HeroAvatar string `protobuf:"bytes,3,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
}

func (x *UserLoginResult) Reset() {
	*x = UserLoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResult) ProtoMessage() {}

func (x *UserLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResult.ProtoReflect.Descriptor instead.
func (*UserLoginResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{14}
}

func (x *UserLoginResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLoginResult) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserLoginResult) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

//
// 选择英雄
///////////////////////////////////////////////////////////////////////
// 指令
type SelectHeroCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 英雄形象
	HeroAvatar string `protobuf:"bytes,1,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
}

func (x *SelectHeroCmd) Reset() {
	*x = SelectHeroCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectHeroCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectHeroCmd) ProtoMessage() {}

func (x *SelectHeroCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectHeroCmd.ProtoReflect.Descriptor instead.
func (*SelectHeroCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{15}
}

func (x *SelectHeroCmd) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

// 结果
type SelectHeroResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 英雄形象,
	// 如果是空字符串则说明失败
	HeroAvatar string `protobuf:"bytes,1,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
}

func (x *SelectHeroResult) Reset() {
	*x = SelectHeroResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectHeroResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectHeroResult) ProtoMessage() {}

func (x *SelectHeroResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectHeroResult.ProtoReflect.Descriptor instead.
func (*SelectHeroResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{16}
}

func (x *SelectHeroResult) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

//
// 获取排行榜
///////////////////////////////////////////////////////////////////////
// 指令
type GetRankCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRankCmd) Reset() {
	*x = GetRankCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankCmd) ProtoMessage() {}

func (x *GetRankCmd) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankCmd.ProtoReflect.Descriptor instead.
func (*GetRankCmd) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{17}
}

// 结果
type GetRankResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 排名条目
	RankItem []*GetRankResult_RankItem `protobuf:"bytes,1,rep,name=rankItem,proto3" json:"rankItem,omitempty"`
}

func (x *GetRankResult) Reset() {
	*x = GetRankResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResult) ProtoMessage() {}

func (x *GetRankResult) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResult.ProtoReflect.Descriptor instead.
func (*GetRankResult) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{18}
}

func (x *GetRankResult) GetRankItem() []*GetRankResult_RankItem {
	if x != nil {
		return x.RankItem
	}
	return nil
}

// 用户信息
type WhoElseIsHereResult_UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户 Id
	UserId uint32 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户名称
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// 英雄形象
	HeroAvatar string `protobuf:"bytes,3,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
	// 移动状态
	MoveState *WhoElseIsHereResult_UserInfo_MoveState `protobuf:"bytes,4,opt,name=moveState,proto3" json:"moveState,omitempty"`
}

func (x *WhoElseIsHereResult_UserInfo) Reset() {
	*x = WhoElseIsHereResult_UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoElseIsHereResult_UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoElseIsHereResult_UserInfo) ProtoMessage() {}

func (x *WhoElseIsHereResult_UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoElseIsHereResult_UserInfo.ProtoReflect.Descriptor instead.
func (*WhoElseIsHereResult_UserInfo) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WhoElseIsHereResult_UserInfo) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WhoElseIsHereResult_UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WhoElseIsHereResult_UserInfo) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

func (x *WhoElseIsHereResult_UserInfo) GetMoveState() *WhoElseIsHereResult_UserInfo_MoveState {
	if x != nil {
		return x.MoveState
	}
	return nil
}

// 移动状态
type WhoElseIsHereResult_UserInfo_MoveState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 起始位置 X
	FromPosX float32 `protobuf:"fixed32,1,opt,name=fromPosX,proto3" json:"fromPosX,omitempty"`
	// 起始位置 Y
	FromPosY float32 `protobuf:"fixed32,2,opt,name=fromPosY,proto3" json:"fromPosY,omitempty"`
	// 移动到位置 X
	ToPosX float32 `protobuf:"fixed32,3,opt,name=toPosX,proto3" json:"toPosX,omitempty"`
	// 移动到位置 Y
	ToPosY float32 `protobuf:"fixed32,4,opt,name=toPosY,proto3" json:"toPosY,omitempty"`
	// 启程时间戳
	StartTime uint64 `protobuf:"varint,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) Reset() {
	*x = WhoElseIsHereResult_UserInfo_MoveState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoElseIsHereResult_UserInfo_MoveState) ProtoMessage() {}

func (x *WhoElseIsHereResult_UserInfo_MoveState) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoElseIsHereResult_UserInfo_MoveState.ProtoReflect.Descriptor instead.
func (*WhoElseIsHereResult_UserInfo_MoveState) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) GetFromPosX() float32 {
	if x != nil {
		return x.FromPosX
	}
	return 0
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) GetFromPosY() float32 {
	if x != nil {
		return x.FromPosY
	}
	return 0
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) GetToPosX() float32 {
	if x != nil {
		return x.ToPosX
	}
	return 0
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) GetToPosY() float32 {
	if x != nil {
		return x.ToPosY
	}
	return 0
}

func (x *WhoElseIsHereResult_UserInfo_MoveState) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// 用户信息
type GetRankResult_RankItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 排名 Id
	RankId uint32 `protobuf:"varint,1,opt,name=rankId,proto3" json:"rankId,omitempty"`
	// 用户 Id
	UserId uint32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// 用户名称
	UserName string `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	// 英雄形象
	HeroAvatar string `protobuf:"bytes,4,opt,name=heroAvatar,proto3" json:"heroAvatar,omitempty"`
	// 胜利次数
	Win uint32 `protobuf:"varint,5,opt,name=win,proto3" json:"win,omitempty"`
}

func (x *GetRankResult_RankItem) Reset() {
	*x = GetRankResult_RankItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsgProtocol_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRankResult_RankItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRankResult_RankItem) ProtoMessage() {}

func (x *GetRankResult_RankItem) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsgProtocol_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRankResult_RankItem.ProtoReflect.Descriptor instead.
func (*GetRankResult_RankItem) Descriptor() ([]byte, []int) {
	return file_GameMsgProtocol_proto_rawDescGZIP(), []int{18, 0}
}

func (x *GetRankResult_RankItem) GetRankId() uint32 {
	if x != nil {
		return x.RankId
	}
	return 0
}

func (x *GetRankResult_RankItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetRankResult_RankItem) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GetRankResult_RankItem) GetHeroAvatar() string {
	if x != nil {
		return x.HeroAvatar
	}
	return ""
}

func (x *GetRankResult_RankItem) GetWin() uint32 {
	if x != nil {
		return x.Win
	}
	return 0
}

var File_GameMsgProtocol_proto protoreflect.FileDescriptor

var file_GameMsgProtocol_proto_rawDesc = []byte{
	0x0a, 0x15, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0e, 0x0a, 0x0c,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6d, 0x64, 0x22, 0x65, 0x0a, 0x0f,
	0x55, 0x73, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x22, 0x12, 0x0a, 0x10, 0x57, 0x68, 0x6f, 0x45, 0x6c, 0x73, 0x65, 0x49, 0x73,
	0x48, 0x65, 0x72, 0x65, 0x43, 0x6d, 0x64, 0x22, 0x94, 0x03, 0x0a, 0x13, 0x57, 0x68, 0x6f, 0x45,
	0x6c, 0x73, 0x65, 0x49, 0x73, 0x48, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x3d, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x57, 0x68, 0x6f, 0x45, 0x6c, 0x73, 0x65, 0x49,
	0x73, 0x48, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xbd,
	0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x49, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x57, 0x68, 0x6f, 0x45, 0x6c, 0x73, 0x65,
	0x49, 0x73, 0x48, 0x65, 0x72, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x09, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x91, 0x01, 0x0a, 0x09, 0x4d,
	0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x58, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x59,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x59,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x50, 0x6f,
	0x73, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x6f, 0x50, 0x6f, 0x73, 0x59,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x97,
	0x01, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x43, 0x6d, 0x64,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x58,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x58, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x50, 0x6f, 0x73, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x59, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65,
	0x54, 0x6f, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6d, 0x6f,
	0x76, 0x65, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65,
	0x54, 0x6f, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6d, 0x6f,
	0x76, 0x65, 0x54, 0x6f, 0x50, 0x6f, 0x73, 0x59, 0x22, 0xe0, 0x01, 0x0a, 0x10, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73,
	0x58, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x50, 0x6f, 0x73,
	0x59, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x50, 0x6f, 0x73, 0x59, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x50,
	0x6f, 0x73, 0x58, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x6f, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x50,
	0x6f, 0x73, 0x59, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x6f, 0x50, 0x6f, 0x73, 0x59, 0x12, 0x24, 0x0a, 0x0d, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6d, 0x6f,
	0x76, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x0e, 0x55,
	0x73, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x71, 0x75, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0a, 0x71, 0x75, 0x69, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x0d, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x43, 0x6d, 0x64, 0x22, 0x70, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x41, 0x74, 0x50, 0x6f, 0x73, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x41, 0x74, 0x50, 0x6f, 0x73, 0x58, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x41, 0x74, 0x50, 0x6f, 0x73, 0x59, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x70, 0x41, 0x74, 0x50, 0x6f, 0x73, 0x59, 0x22, 0x31,
	0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x6b, 0x43, 0x6d, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x54, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x6b, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x48, 0x70, 0x22, 0x33, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72, 0x44, 0x69, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6d, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x65, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x72,
	0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x2f, 0x0a, 0x0d, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x48, 0x65, 0x72, 0x6f, 0x43, 0x6d, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x68, 0x65,
	0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x32, 0x0a, 0x10, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x48, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x0c, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x43, 0x6d, 0x64, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x37, 0x0a, 0x08,
	0x72, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x72, 0x61, 0x6e,
	0x6b, 0x49, 0x74, 0x65, 0x6d, 0x1a, 0x88, 0x01, 0x0a, 0x08, 0x52, 0x61, 0x6e, 0x6b, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x77, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x77, 0x69, 0x6e,
	0x2a, 0xb3, 0x03, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x00,
	0x12, 0x15, 0x0a, 0x11, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x45, 0x4e, 0x54, 0x52, 0x59, 0x5f, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x57, 0x48, 0x4f, 0x5f, 0x45,
	0x4c, 0x53, 0x45, 0x5f, 0x49, 0x53, 0x5f, 0x48, 0x45, 0x52, 0x45, 0x5f, 0x43, 0x4d, 0x44, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x57, 0x48, 0x4f, 0x5f, 0x45, 0x4c, 0x53, 0x45, 0x5f, 0x49, 0x53,
	0x5f, 0x48, 0x45, 0x52, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x03, 0x12, 0x14,
	0x0a, 0x10, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x43,
	0x4d, 0x44, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x56,
	0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x05, 0x12, 0x14, 0x0a,
	0x10, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x51, 0x55, 0x49, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c,
	0x54, 0x10, 0x06, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x4f, 0x50,
	0x5f, 0x43, 0x4d, 0x44, 0x10, 0x07, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53,
	0x54, 0x4f, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x08, 0x12, 0x11, 0x0a, 0x0d,
	0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54, 0x4b, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x09, 0x12,
	0x14, 0x0a, 0x10, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x54, 0x54, 0x4b, 0x5f, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x10, 0x0a, 0x12, 0x1b, 0x0a, 0x17, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x53, 0x55,
	0x42, 0x54, 0x52, 0x41, 0x43, 0x54, 0x5f, 0x48, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x10, 0x0b, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x44, 0x49, 0x45, 0x5f, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x0c, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x0d, 0x12, 0x15, 0x0a, 0x11, 0x55,
	0x53, 0x45, 0x52, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54,
	0x10, 0x0e, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x5f, 0x48, 0x45, 0x52,
	0x4f, 0x5f, 0x43, 0x4d, 0x44, 0x10, 0x0f, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x4c, 0x45, 0x43,
	0x54, 0x5f, 0x48, 0x45, 0x52, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x10, 0x12,
	0x10, 0x0a, 0x0c, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x43, 0x4d, 0x44, 0x10,
	0x11, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x5f, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x10, 0x12, 0x42, 0x23, 0x0a, 0x1a, 0x6f, 0x72, 0x67, 0x2e, 0x74, 0x69,
	0x6e, 0x79, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x2e, 0x6d, 0x73, 0x67, 0x5a, 0x05, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_GameMsgProtocol_proto_rawDescOnce sync.Once
	file_GameMsgProtocol_proto_rawDescData = file_GameMsgProtocol_proto_rawDesc
)

func file_GameMsgProtocol_proto_rawDescGZIP() []byte {
	file_GameMsgProtocol_proto_rawDescOnce.Do(func() {
		file_GameMsgProtocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_GameMsgProtocol_proto_rawDescData)
	})
	return file_GameMsgProtocol_proto_rawDescData
}

var file_GameMsgProtocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_GameMsgProtocol_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_GameMsgProtocol_proto_goTypes = []interface{}{
	(MsgCode)(0),                                   // 0: msg.MsgCode
	(*UserEntryCmd)(nil),                           // 1: msg.UserEntryCmd
	(*UserEntryResult)(nil),                        // 2: msg.UserEntryResult
	(*WhoElseIsHereCmd)(nil),                       // 3: msg.WhoElseIsHereCmd
	(*WhoElseIsHereResult)(nil),                    // 4: msg.WhoElseIsHereResult
	(*UserMoveToCmd)(nil),                          // 5: msg.UserMoveToCmd
	(*UserMoveToResult)(nil),                       // 6: msg.UserMoveToResult
	(*UserQuitResult)(nil),                         // 7: msg.UserQuitResult
	(*UserStopCmd)(nil),                            // 8: msg.UserStopCmd
	(*UserStopResult)(nil),                         // 9: msg.UserStopResult
	(*UserAttkCmd)(nil),                            // 10: msg.UserAttkCmd
	(*UserAttkResult)(nil),                         // 11: msg.UserAttkResult
	(*UserSubtractHpResult)(nil),                   // 12: msg.UserSubtractHpResult
	(*UserDieResult)(nil),                          // 13: msg.UserDieResult
	(*UserLoginCmd)(nil),                           // 14: msg.UserLoginCmd
	(*UserLoginResult)(nil),                        // 15: msg.UserLoginResult
	(*SelectHeroCmd)(nil),                          // 16: msg.SelectHeroCmd
	(*SelectHeroResult)(nil),                       // 17: msg.SelectHeroResult
	(*GetRankCmd)(nil),                             // 18: msg.GetRankCmd
	(*GetRankResult)(nil),                          // 19: msg.GetRankResult
	(*WhoElseIsHereResult_UserInfo)(nil),           // 20: msg.WhoElseIsHereResult.UserInfo
	(*WhoElseIsHereResult_UserInfo_MoveState)(nil), // 21: msg.WhoElseIsHereResult.UserInfo.MoveState
	(*GetRankResult_RankItem)(nil),                 // 22: msg.GetRankResult.RankItem
}
var file_GameMsgProtocol_proto_depIdxs = []int32{
	20, // 0: msg.WhoElseIsHereResult.userInfo:type_name -> msg.WhoElseIsHereResult.UserInfo
	22, // 1: msg.GetRankResult.rankItem:type_name -> msg.GetRankResult.RankItem
	21, // 2: msg.WhoElseIsHereResult.UserInfo.moveState:type_name -> msg.WhoElseIsHereResult.UserInfo.MoveState
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_GameMsgProtocol_proto_init() }
func file_GameMsgProtocol_proto_init() {
	if File_GameMsgProtocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GameMsgProtocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEntryCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserEntryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoElseIsHereCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoElseIsHereResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMoveToCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMoveToResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserQuitResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStopCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserStopResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAttkCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAttkResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserSubtractHpResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserDieResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserLoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectHeroCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectHeroResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoElseIsHereResult_UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoElseIsHereResult_UserInfo_MoveState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsgProtocol_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRankResult_RankItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GameMsgProtocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMsgProtocol_proto_goTypes,
		DependencyIndexes: file_GameMsgProtocol_proto_depIdxs,
		EnumInfos:         file_GameMsgProtocol_proto_enumTypes,
		MessageInfos:      file_GameMsgProtocol_proto_msgTypes,
	}.Build()
	File_GameMsgProtocol_proto = out.File
	file_GameMsgProtocol_proto_rawDesc = nil
	file_GameMsgProtocol_proto_goTypes = nil
	file_GameMsgProtocol_proto_depIdxs = nil
}
